### ISSUE TITLE
MDX Extension for VSCode doesn't support IntelliSense link path completion for # and ## triggers in .mdx files

### ISSUE THREAD

**Issue by yokaiichi** [mdx-js/mdx-analyzer#482]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

MDX unified v1.8.11

### Steps to reproduce

1. On a Mac system, install VSCode 1.94.0 or later, and install the MDX unified Extension v1.8.11.

2. In a repo, create two sibling folders. In one folder place two files A.mdx and B.mdx. In the other folder place a single file C.mdx.

3. In A.mdx create several different ## sections and dummy paragraphs in each section. Do the same for B.mdx and C.mdx.

4. In A.mdx, in any paragraph, add an empty Markdown link `[anchorText]()`. Place your cursor in the empty link destination delimiters `()`, trigger IntelliSense autocomplete (Control + Space) and type `#` to attempt to view autocomplete link paths to headers within the same A.mdx file. Nothing will happen; IntelliSense is not recognizing the `#` trigger.

5. Try a variation of this by removing the `#` and this time typing two hash marks `##` to attemp to view autocomplete link paths to headers across ALL files including B.mdx and C.mdx. Nothing will happen; IntelliSense is not recognizing the `##` trigger.

6. Now try all this again with three non-MDX files A.md, B.md, and C.md. You'll see that IntelliSense fully recognizes and acts on both the `#` and `##` triggers in regular .md files.

### Expected behavior

IntelliSense recognizes both `#` and `##` triggers for _link path completion_ behavior, exactly as it does in regular .md files.

[Additional details from Discussion in mdx-js](https://github.com/orgs/mdx-js/discussions/2557)

### Actual behavior

IntelliSense does absolutely nothing in response to `#` and `##` triggers for _link path completion_ in .mdx files, even with the most recent (v1.8.11) MDX unified Extension installed in the most recent version of VSCode (v1.94.0) for Mac.

### Affected runtime and version

node v20.18.0 

### Affected package manager and version

npm v10.9.0

### Affected OS and version

macOS Sonoma 14.6.1

### Build and bundle tools

Docusaurus

**Comment by remcohaszing** [comment]
Some findings based on [`fixtures/demo/fixture.mdx`](https://github.com/mdx-js/mdx-analyzer/blob/main/fixtures/demo/fixture.mdx), where `|` represents the cursor position:

- The `#` character does trigger completions.
- Headings are resolved for relative paths to `.mdx` files (`[](./fixtures.mdx#|`)
- Headings are **not** resolved for relative paths to `.md` files (`[](../../README.md#|`)
- Headings are **not** resolved within the same file (`[](#|`)

**Comment by yokaiichi** [comment]
Not sure exactly what you mean with the first bullet, but it's outside the scope of the problem I reported anyway. Which revolves around what you've _partially_ confirmed in the 3rd and 4th bullets.  

However, there is one other aspect of my reported behavior that isn't reflected in your findings (yet):

- Headings _within other files_ are not resolved for relative paths to .md files ([](../../README.md##|) - Note the double-hash trigger.
- Headings are not resolved _within other files_ ([](##|) - Note the double-hash trigger.

Both your 3rd and 4th bullets, and these two just above, work correctly for `.md` files in VSCode.
